### ISSUE TITLE
Refresh Client list

### ISSUE THREAD

**Issue by masseym** [mikedamage/hayfever-chrome#28]
I cannot figure out how to update the client list.  I added a new client via the website and want to track time for them. There is no way to update the list nor does it seem to have pulled an updated list within the last hour.

**Comment by mikedamage** [comment]
You can refresh the client list by clicking the refresh icon at the bottom of the timers table. If that doesn't work, we've got a bug. Can you try it and let me know?

**Comment by masseym** [comment]
I figured out what was wrong. For some reason my task was not saved in harvest. Sorry about that.



On Jan 1, 2015, at 9:27 PM, Mike Green <notifications@github.com<mailto:notifications@github.com>> wrote:


You can refresh the client list by clicking the refresh icon at the bottom of the timers table. If that doesn't work, we've got a bug. Can you try it and let me know?

**Comment by mikedamage** [comment]
No problem, thanks for using Hayfever!
